### ISSUE TITLE
Аналитика использования бота

### ISSUE THREAD

**Issue by yvalinurova** [glebdubanov/school216bot#1]
Добавь сбор статистики. Например, сколько человек им пользуются? Какие разделы наиболее популярны?

**Comment by glebdubanov** [comment]
Я в код добавил команду для сервиса graspil.com, которая заменяет API Telegram на API сервиса graspil.com. Сам сервис высчитывает статистику телеграм-ботов, сколько пользователей, новые, постоянные и ушедшие, кол-во сессий, сообщений и т.д.
